/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
<<<<<<< Updated upstream
import { Route as UserSign_inUserRouteImport } from './routes/user/sign_in/user'
import { Route as UserSign_inRegisterRouteImport } from './routes/user/sign_in/register'
=======
import { Route as BookingRoomsIndexRouteImport } from './routes/booking/rooms.index'
>>>>>>> Stashed changes
import { Route as BookingRoomsRoomIdRouteImport } from './routes/booking/rooms.$roomId'
import { Route as BookingBookingBookingIdRouteImport } from './routes/booking/booking.$bookingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< Updated upstream
const UserSign_inUserRoute = UserSign_inUserRouteImport.update({
  id: '/user/sign_in/user',
  path: '/user/sign_in/user',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSign_inRegisterRoute = UserSign_inRegisterRouteImport.update({
  id: '/user/sign_in/register',
  path: '/user/sign_in/register',
=======
const BookingRoomsIndexRoute = BookingRoomsIndexRouteImport.update({
  id: '/booking/rooms/',
  path: '/booking/rooms/',
>>>>>>> Stashed changes
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoomsRoomIdRoute = BookingRoomsRoomIdRouteImport.update({
  id: '/booking/rooms/$roomId',
  path: '/booking/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingBookingBookingIdRoute = BookingBookingBookingIdRouteImport.update({
  id: '/booking/booking/$bookingId',
  path: '/booking/booking/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking/booking/$bookingId': typeof BookingBookingBookingIdRoute
  '/booking/rooms/$roomId': typeof BookingRoomsRoomIdRoute
<<<<<<< Updated upstream
  '/user/sign_in/register': typeof UserSign_inRegisterRoute
  '/user/sign_in/user': typeof UserSign_inUserRoute
=======
  '/booking/rooms': typeof BookingRoomsIndexRoute
>>>>>>> Stashed changes
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking/booking/$bookingId': typeof BookingBookingBookingIdRoute
  '/booking/rooms/$roomId': typeof BookingRoomsRoomIdRoute
<<<<<<< Updated upstream
  '/user/sign_in/register': typeof UserSign_inRegisterRoute
  '/user/sign_in/user': typeof UserSign_inUserRoute
=======
  '/booking/rooms': typeof BookingRoomsIndexRoute
>>>>>>> Stashed changes
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking/booking/$bookingId': typeof BookingBookingBookingIdRoute
  '/booking/rooms/$roomId': typeof BookingRoomsRoomIdRoute
<<<<<<< Updated upstream
  '/user/sign_in/register': typeof UserSign_inRegisterRoute
  '/user/sign_in/user': typeof UserSign_inUserRoute
=======
  '/booking/rooms/': typeof BookingRoomsIndexRoute
>>>>>>> Stashed changes
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking/booking/$bookingId'
    | '/booking/rooms/$roomId'
<<<<<<< Updated upstream
    | '/user/sign_in/register'
    | '/user/sign_in/user'
=======
    | '/booking/rooms'
>>>>>>> Stashed changes
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking/booking/$bookingId'
    | '/booking/rooms/$roomId'
<<<<<<< Updated upstream
    | '/user/sign_in/register'
    | '/user/sign_in/user'
=======
    | '/booking/rooms'
>>>>>>> Stashed changes
  id:
    | '__root__'
    | '/'
    | '/booking/booking/$bookingId'
    | '/booking/rooms/$roomId'
<<<<<<< Updated upstream
    | '/user/sign_in/register'
    | '/user/sign_in/user'
=======
    | '/booking/rooms/'
>>>>>>> Stashed changes
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingBookingBookingIdRoute: typeof BookingBookingBookingIdRoute
  BookingRoomsRoomIdRoute: typeof BookingRoomsRoomIdRoute
<<<<<<< Updated upstream
  UserSign_inRegisterRoute: typeof UserSign_inRegisterRoute
  UserSign_inUserRoute: typeof UserSign_inUserRoute
=======
  BookingRoomsIndexRoute: typeof BookingRoomsIndexRoute
>>>>>>> Stashed changes
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< Updated upstream
    '/user/sign_in/user': {
      id: '/user/sign_in/user'
      path: '/user/sign_in/user'
      fullPath: '/user/sign_in/user'
      preLoaderRoute: typeof UserSign_inUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/sign_in/register': {
      id: '/user/sign_in/register'
      path: '/user/sign_in/register'
      fullPath: '/user/sign_in/register'
      preLoaderRoute: typeof UserSign_inRegisterRouteImport
=======
    '/booking/rooms/': {
      id: '/booking/rooms/'
      path: '/booking/rooms'
      fullPath: '/booking/rooms'
      preLoaderRoute: typeof BookingRoomsIndexRouteImport
>>>>>>> Stashed changes
      parentRoute: typeof rootRouteImport
    }
    '/booking/rooms/$roomId': {
      id: '/booking/rooms/$roomId'
      path: '/booking/rooms/$roomId'
      fullPath: '/booking/rooms/$roomId'
      preLoaderRoute: typeof BookingRoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/booking/$bookingId': {
      id: '/booking/booking/$bookingId'
      path: '/booking/booking/$bookingId'
      fullPath: '/booking/booking/$bookingId'
      preLoaderRoute: typeof BookingBookingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingBookingBookingIdRoute: BookingBookingBookingIdRoute,
  BookingRoomsRoomIdRoute: BookingRoomsRoomIdRoute,
<<<<<<< Updated upstream
  UserSign_inRegisterRoute: UserSign_inRegisterRoute,
  UserSign_inUserRoute: UserSign_inUserRoute,
=======
  BookingRoomsIndexRoute: BookingRoomsIndexRoute,
>>>>>>> Stashed changes
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
