/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingRoomsRoomIdRouteImport } from './routes/booking/rooms.$roomId'
import { Route as BookingBookingBookingIdRouteImport } from './routes/booking/booking.$bookingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoomsRoomIdRoute = BookingRoomsRoomIdRouteImport.update({
  id: '/booking/rooms/$roomId',
  path: '/booking/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingBookingBookingIdRoute = BookingBookingBookingIdRouteImport.update({
  id: '/booking/booking/$bookingId',
  path: '/booking/booking/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking/booking/$bookingId': typeof BookingBookingBookingIdRoute
  '/booking/rooms/$roomId': typeof BookingRoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking/booking/$bookingId': typeof BookingBookingBookingIdRoute
  '/booking/rooms/$roomId': typeof BookingRoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking/booking/$bookingId': typeof BookingBookingBookingIdRoute
  '/booking/rooms/$roomId': typeof BookingRoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/booking/booking/$bookingId' | '/booking/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/booking/booking/$bookingId' | '/booking/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/booking/booking/$bookingId'
    | '/booking/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingBookingBookingIdRoute: typeof BookingBookingBookingIdRoute
  BookingRoomsRoomIdRoute: typeof BookingRoomsRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/rooms/$roomId': {
      id: '/booking/rooms/$roomId'
      path: '/booking/rooms/$roomId'
      fullPath: '/booking/rooms/$roomId'
      preLoaderRoute: typeof BookingRoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/booking/$bookingId': {
      id: '/booking/booking/$bookingId'
      path: '/booking/booking/$bookingId'
      fullPath: '/booking/booking/$bookingId'
      preLoaderRoute: typeof BookingBookingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingBookingBookingIdRoute: BookingBookingBookingIdRoute,
  BookingRoomsRoomIdRoute: BookingRoomsRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
